name: AI-Augmented Issue
description: AI-assisted issue reporting with auto-suggestions.
title: "[Type] Short Description"
labels: []
assignees: []

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "Issue Type"
      description: "Select the type of work"
      options:
        - "🔹 Feature"
        - "⚡ Enhancement"
        - "🐞 Bug"
        - "🚨 Incident"
        - "🛡️ Security Fix"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a brief summary of the issue."
      placeholder: "Describe the problem or feature request in one or two sentences."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Provide additional details, including expected behavior, current behavior, and any related links."
      placeholder: "Explain the context of this issue in more detail."
    validations:
      required: true

  - type: textarea
    id: logs_errors
    attributes:
      label: "Logs / Errors (Auto-Extracted by AI)"
      description: "AI can extract relevant logs/errors from linked monitoring tools."
      placeholder: "Logs will be auto-filled if available."
    validations:
      required: false

  - type: textarea
    id: ai_insights
    attributes:
      label: "🔍 AI Insights & Suggestions"
      description: "AI-generated analysis of root causes and recommended fixes."
      placeholder: "AI will suggest possible root causes, fixes, or related issues."
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce (For Bugs/Incidents)"
      description: "If this is a bug or incident, provide steps to reproduce."
      placeholder: |
        1. Run command `kubectl apply -f deployment.yaml`
        2. Observe error in logs
        3. Service fails to start
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level (AI Suggested)"
      description: "AI can assess the impact and suggest priority."
      options:
        - "🟥 P0 (Critical – Requires Immediate Action)"
        - "🟧 P1 (High – Next Sprint)"
        - "🟨 P2 (Medium – Planned Work)"
        - "🟩 P3 (Low – Nice to Have)"
    validations:
      required: true

  - type: dropdown
    id: affected_component
    attributes:
      label: "Affected Component (AI Suggested)"
      description: "AI can auto-categorize affected components."
      options:
        - "🚀 Kubernetes Cluster"
        - "📦 Helm Charts"
        - "⚙️ Terraform Modules"
        - "🔐 Security & Compliance"
        - "📊 Monitoring & Alerts"
        - "📜 Documentation"
    validations:
      required: true

  - type: checkboxes
    id: dependencies
    attributes:
      label: "Dependencies & Impact (AI Suggested)"
      description: "AI can suggest related issues or dependencies."
      options:
        - label: "Blocks another issue"
        - label: "Blocked by another issue"
        - label: "Impacts security compliance"
        - label: "Requires documentation updates"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Add any extra context, screenshots, or references."
    validations:
      required: false
