name: "💡 Feature Request"
description: Create a new feature request
title: "💡 [FR] - As a <persona> I want the ability to <verb> these <objects/actions>"
labels: [
  "enhancement"
]
projects: [ "rljohnsn/1"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: |
        "Describe in a few lines your feature request. 

        ## Motivation
        > As a <persona>,
        > I want the ability to <verb> these <objects/actions>,
        > so that <purpose>

        ## Specification
        Here you can go into more details and even potential psuedo code

        ```hcl
        resource "aws_instance" "ec2" {
          ami               = var.ami
          availability_zone = var.availability_zone
        } 
        ```
        "

    validations:
      required: true
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "month/day/year"
    validations:
      required: false
  - type: textarea
    id: deliverables
    attributes:
      label: "Deliverables"
      description: Describe the tangible items or capabilities provided by this feature.
      placeholder: |
        Create a list of deliverables about your feature request.

        - [ ] deliverable 1
        - [ ] deliverable 2

    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: How would someone indepently confirm the features deliverables ?
      placeholder: |
        Create a list describing ways to confirm your feature request

        - [ ] how to validate deliverable 1
        - [ ] how to validate deliverable 2
        
    validations:
      required: true
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
